# Generated by Django 4.0.5 on 2022-08-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('publication_date', models.DateField()),
                ('subject_area', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('status', models.CharField(default='Available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('email_address', models.EmailField(default='somoneone@gmail.com', max_length=254, verbose_name='Email Field')),
                ('fine', models.BooleanField(default=False)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
