# Generated by Django 4.0.5 on 2022-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='fine',
            field=models.CharField(choices=[('None', 'None'), ('5000', '5000'), ('10000', '10000'), ('15000', '15000')], default='None', max_length=6),
        ),
    ]
