# Generated by Django 4.0.5 on 2022-08-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_borrow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Field'),
        ),
    ]
